name: CI - Pipeline Informatif

on: 
  push:
    branches:
      - main

jobs:
  integration-continue: 
    name: Démonstration CI 
    runs-on: ubuntu-latest
  
    env:
      lola: "merci beaucoup"

    steps:
      - name: Étape 1 - Initialisation 
        run:  |
          echo "Démarrage du pipeline d'intégration continue"
      - name: Étape 2 - Récupération du code 
        run:  |
          echo "Récupération du code source"
          echo "${{vars.MAIMOUNA}}" 
      - name: Etape 3 - Build
        run:  |
          echo "Phase de build"
          echo "Compilation ou construction de l'application"
          echo "fin du cours $lola"
          echo "${{secrets.Fast_Food}}"
    
